//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@class CContact, MMTableViewInfo;

@interface ChatRoomAdminListViewController : MMUIViewController
{
    MMTableViewInfo *m_tableViewInfo;
    CContact *_chatRoomContact;
}

@property(retain, nonatomic) CContact *chatRoomContact; // @synthesize chatRoomContact=_chatRoomContact;
- (void).cxx_destruct;
- (void)onClickContactsItem:(id)arg1;
- (void)makeContactCell:(id)arg1 CellInfo:(id)arg2;
- (void)reloadTableData;
- (void)initTableView;
- (void)viewDidLoad;

@end

