//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EmojiInfoObj, EmoticonAddToServerLogicObject;

@protocol EmoticonAddToServerLogicDelegate <NSObject>

@optional
- (void)onEmoticonAddToServerFailed:(EmoticonAddToServerLogicObject *)arg1 reason:(unsigned long long)arg2;
- (void)onEmoticonAddToServerOk:(EmoticonAddToServerLogicObject *)arg1 emojiInfo:(EmojiInfoObj *)arg2;
@end

