//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PayMenuRedDotHelper : NSObject
{
}

+ (void)clearRedDotAtMe;
+ (void)clearRedDotAtWalletWithReport:(_Bool)arg1;
+ (void)clearRedDotAtWallet;
+ (void)clearRedDotAtPayCenter;
+ (id)wordingAtWallet;
+ (_Bool)showRedDotAtMe;
+ (_Bool)showRedDotAtWallet;
+ (_Bool)showRedDotAtPayCenter;
+ (void)clearPayMenuRedDotForName:(id)arg1;
+ (_Bool)showRedDotAtName:(id)arg1;
+ (id)getNewRedDotInfo;
+ (id)getRedDotInfo;
+ (void)handleMsg:(id)arg1;

@end

