//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, UIBezierPath, UIColor;

@interface WCSVGStyledPath : NSObject
{
    NSNumber *_opacity;
    UIBezierPath *_path;
    UIColor *_fillColor;
    UIColor *_strokeColor;
    NSArray *_affineTransforms;
    double _strokeWidth;
}

+ (id)styledPathWithPath:(id)arg1 fillColor:(id)arg2 strokeColor:(id)arg3 strokeWidth:(double)arg4 affineTransforms:(id)arg5 opacity:(id)arg6;
@property(nonatomic) double strokeWidth; // @synthesize strokeWidth=_strokeWidth;
@property(retain, nonatomic) NSArray *affineTransforms; // @synthesize affineTransforms=_affineTransforms;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(retain, nonatomic) UIBezierPath *path; // @synthesize path=_path;
@property(retain, nonatomic) NSNumber *opacity; // @synthesize opacity=_opacity;
- (void).cxx_destruct;
- (id)description;
- (void)drawStyledPathInContext:(struct CGContext *)arg1 tintColor:(id)arg2;

@end

