//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WSVideoFlowBaseDelegate.h"

@class NSString, UIGestureRecognizer;

@protocol WSVideoPagingPlayerViewDelegate <WSVideoFlowBaseDelegate>

@optional
- (_Bool)canPlayNextVideo;
- (void)onPlayerViewResetAndPlay;
- (void)onPlayerViewClickToPlay;
- (void)onPlayerViewReplayForUpdatedUrl;
- (_Bool)onPlayerViewUpdateVideoUrl:(NSString *)arg1;
- (void)onPlayerViewPlayToEnd:(id)arg1;
- (void)onVideoPanGestureEndOrCancel:(UIGestureRecognizer *)arg1;
- (void)onVideoPanGestureMove:(UIGestureRecognizer *)arg1;
- (void)onVideoPanGestureBeginDrag:(UIGestureRecognizer *)arg1;
- (void)onHideControlViews;
- (void)onShowControlViews;
- (void)onClickMaskViewPlayButton;
- (_Bool)canBeginPlayVideoUnderMobileNetwork;
@end

